{
 "title": "OSC / SCONE Status",
 "description": "Visualize Metrics and Alerts of the SCONE Operator",
 "tags": [
  "OSC",
  "SWS",
  "Scone"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cr_name",
    "query": {
     "query": "label_values(scone_cas_state{},cr_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Controller Reconcile Errors",
   "type": "stat",
   "description": "Scone Operator Reconcile Errors over last 24h",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(controller_runtime_reconcile_errors_total{controller=\"scone\"}[24h])",
     "legendFormat": "SCONE Controller"
    },
    {
     "expr": "increase(controller_runtime_reconcile_errors_total{controller=\"sgxplugin\"}[24h])",
     "legendFormat": "SGXPlugin Controller"
    },
    {
     "expr": "increase(controller_runtime_reconcile_errors_total{controller=\"cas\"}[24h])",
     "legendFormat": "CAS Controller"
    },
    {
     "expr": "increase(controller_runtime_reconcile_errors_total{controller=\"las\"}[24h])",
     "legendFormat": "LAS Controller"
    }
   ]
  },
  {
   "title": "LAS Replica Alert",
   "type": "stat",
   "description": "The number of expected LAS pods that are not running.",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "scone_las_las_replica_alert{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "SGXPlugin State",
   "type": "stat",
   "description": "The state of the SGXPlugin. The value HEALTHY indicates the SGXPlugin is running without any detected issues. The value PENDING indicates the SGXPlugin is not yet healthy but no problems have been detected, and it is expected to become healthy without human intervention. The value UNHEALTHY indicates a problem has been detected. ",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "scone_sgxplugin_state{}", "legendFormat": "SGXPlugin State" }
   ]
  },
  {
   "title": "LAS State",
   "type": "stat",
   "description": "The state of the LAS. The value HEALTHY indicates the LAS is running without any detected issues. The value PENDING indicates the LAS is not yet healthy but no problems have been detected, and it is expected to become healthy without human intervention. The value UNHEALTHY indicates a problem has been detected. ",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "scone_las_state{}", "legendFormat": "LAS State" }
   ]
  },
  {
   "title": "Allocatable SGX devices per node",
   "type": "bargauge",
   "description": "Ratio of allocatable (not used) SGX Devices to total number per node.",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(scone_sgxplugin_available_sgx_devices_per_node{})\n/\n(scone_sgxplugin_capacity_sgx_devices_per_node{})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SGX Nodes wo/Device",
   "type": "stat",
   "description": "The number of selected SGX-capable nodes, which has no available devices in the particular device category.",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (sgxDevice) (scone_sgxplugin_sgx_device_alert{})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SGX Nodes wo/SGXPlugin",
   "type": "stat",
   "description": "The number of selected SGX-capable nodes with unavailable SGXPlugin pods.",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scone_sgxplugin_sgx_replica_alert{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "LAS Replica",
   "type": "stat",
   "description": "The desired number of nodes on which a LAS pod has been selected to run, and, the number of nodes with a LAS pod in Ready state.",
   "gridPos": { "h": 7, "w": 3, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scone_las_desired_number_scheduled{}",
     "legendFormat": "Desired"
    },
    { "expr": "scone_las_number_available{}", "legendFormat": "Ready" }
   ]
  },
  {
   "title": "SGXPlugin replicas",
   "type": "stat",
   "description": "The desired number of nodes on which the SGXPlugin has been selected to run, and the number of nodes with a SGXPlugin pod in Ready state.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scone_sgxplugin_desired_replicas{}",
     "legendFormat": "Desired"
    },
    {
     "expr": "scone_sgxplugin_ready_replicas{}",
     "legendFormat": "Ready"
    }
   ]
  },
  { "title": "CAS State", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "CAS State for instance $cr_name",
   "type": "stat",
   "description": "Insights into state of CAS instance $cr_name.",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 11 },
   "repeat": "cr_name",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scone_cas_state{cr_name=\"$cr_name\"}",
     "legendFormat": "State"
    },
    {
     "expr": "scone_cas_migration_node_alert{cr_name=\"$cr_name\"}",
     "legendFormat": "Bckp CAS Missing"
    },
    {
     "expr": "scone_cas_replica_alert{cr_name=\"$cr_name\"}",
     "legendFormat": "Pods not running"
    },
    {
     "expr": "scone_cas_snapshot_alert{cr_name=\"$cr_name\"}",
     "legendFormat": "Snapshots Created"
    },
    {
     "expr": "scone_cas_migration_controller_replica_alert{cr_name=\"$cr_name\"}",
     "legendFormat": "Bckp Ctrlrs Failed"
    },
    {
     "expr": "scone_cas_attestable{cr_name=\"$cr_name\"}",
     "legendFormat": "CAS Attestable"
    }
   ]
  }
 ]
}